### ISSUE TITLE
Relationship with Gradle dependency locking

### ISSUE THREAD

**Issue by pentlander** [tadfisher/gradle2nix#10]
Hi, I'm just wondering how this tool fits in with Gradle's native dependency locking. Is this mostly meant for the case when the target package does not use the native Gradle locking and it needs to be packaged in nixpkgs? This repo uses both, are there advantages to doing that?

**Comment by tadfisher** [comment]
Hi!

As far as this tool is concerned, it has no idea how Gradle or the project specifies its dependency versions, and that's the advantage from the Nix side; we pin dependencies whether they're locked in Gradle or not. If a dependency is locked on the Gradle side, this tool will pin it at the same version, however.

No IDE or build system uses gradle2nix, though, so Gradle dependency locking is still advantageous for developers. I use it because I can update all dependency versions with one Gradle command.

**Comment by pentlander** [comment]
Thanks for the info and thanks for making this, it works great! I was asking because I'm working on setting up CI/CD for a Kotlin web server on NixOS and I was just trying to figure out how to accomplish this. It seems like gradle2nix might not be necessary for my use case of just deploying to a server rather than distributing to other people.

**Comment by pentlander** [comment]
Ahh nevermind I do need it, I didn't realize that build were performed in a sandbox by default. Is there anything I can help out with? Particularly I'd like to make generating the new gradle-env.json faster.
